# Generated by Django 5.1.2 on 2024-11-03 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_expiringtoken_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExpiringToken",
        ),
    ]
